### ISSUE TITLE
Unnecessary call to View?.DeferRefresh in ViewModelBase.cs

### ISSUE THREAD

**Issue by deccer** [Insire/MvvmScarletToolkit#1]
ViewModelBase.cs:122 contains `using (View?.DeferRefresh())`. That could be removed, View will always be null in ViewModelBase.ctor().

**Comment by Insire** [comment]
That is correct. My reason for leaving it in, is as reference for everyone reading the code, on how to udapte the View properly. As adding SortDescriptions, Groupings and Filters to it, will reevalute the view each time one is added. To prevent this from happening, i left this as best practice in there, as it does no harm.

**Comment by Insire** [comment]
removed it. added documentation to the header of the ViewModelBase
